stages:
  prepare:
    cmd: python -m src.data.preprocessor
    deps:
      - data/raw/diabetic_data.csv
      - src/data/preprocessor.py
    outs:
      - data/processed/
      - models/preprocessor.pkl
  
  train_classical:
    cmd: python -m scripts.train_all --model-type classical
    deps:
      - data/processed/
      - src/models/classical.py
    outs:
      - mlruns/
  
  train_ann:
    cmd: python -m scripts.train_all --model-type ann
    deps:
      - data/processed/
      - src/models/ann.py
