FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1

COPY src/ ./src/
COPY api/ ./api/
COPY models/ ./models/
COPY data/ ./data/
COPY params.yaml .
COPY scripts/ ./scripts/
COPY tests/ ./tests/

EXPOSE 8000

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
